# Generated by Django 6.0.3 on 2026-03-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_agendamento_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
    ]
