# Generated by Django 6.0.3 on 2026-03-17 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_agendamento_cancelado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='owner',
            new_name='prestador',
        ),
    ]
