# Generated by Django 6.0.3 on 2026-03-17 19:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_rename_owner_agendamento_prestador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='cliente',
            new_name='nome_cliente',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='data',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='horario',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='observacao',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='servico',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='data_horario',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendamento',
            name='email_cliente',
            field=models.EmailField(default='default@email.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendamento',
            name='telefone_cliente',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
