# Generated by Django 6.0.3 on 2026-03-17 19:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_rename_cliente_agendamento_nome_cliente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='prestador',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='cancelado',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
