# Generated by Django 6.0.3 on 2026-03-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_rename_prestador_agendamento_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='usuario',
            new_name='prestador',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
    ]
