# Generated by Django 6.0.3 on 2026-03-17 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_rename_usuario_agendamento_prestador_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='cancelado',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='estado',
            field=models.CharField(choices=[('NAO_CONFIRMADO', 'Não confirmado'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado'), ('EXECUTADO', 'Executado')], default='NAO_CONFIRMADO', max_length=20),
        ),
        migrations.CreateModel(
            name='Fidelidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.PositiveIntegerField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fidelidades_cliente', to=settings.AUTH_USER_MODEL)),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fidelidades_prestador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('cliente', 'prestador')},
            },
        ),
    ]
